name: integracion continua con node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  ci_to_master:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: v18.16.0
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Start server
        run: npm start


      
