name: integracion continua con node.js

on:
  pull_request:
    branches: [ main ]

jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build

      - name: Send Slack notification
        uses:  
        env:
          SLACK_BOT_TOKEN: ${{ xoxe.xoxp-1-Mi0yLTQ5NDY5MDg4NDgxODAtNDk1NzA2ODk5NDY3My01NDE4OTEzMTM5MDI1LTU0Mjk5ODIyODM1MDQtZWQ1NWM4NGUxOTk1ODJiNDdjNzBhZGI5MDk2OTY5N2FiMDQ5MDliNTYyOTA3NTYyZjhlMmRjMzM3OWU2OGVmOA }}
        with:
          channel: ci-cd  
          message: "Las pruebas se han ejecutado correctamente en la rama main."  